 Traceback (most recent call last):
   File "gui.py", line 172, in build
     subprocess.check_output(["pidof", "roscore"])
 NameError: name 'subprocess' is not defined
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "gui.py", line 436, in <module>
     MainApp().run()
   File "/home/iascr/.local/lib/python3.8/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/home/iascr/.local/lib/python3.8/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
   File "gui.py", line 173, in build
     except subprocess.CalledProcessError:
 NameError: name 'subprocess' is not defined
[INFO   ] signal_shutdown [atexit]
